### ISSUE TITLE
more explanation needed for heater

### ISSUE THREAD

**Issue by g1ra** [boeserfrosch/GuL_TI_Humidity#2]
I'm anxious leaving enable heater on , as I don't know if heater can be left on all the time or when should the heater be disabled . 
Please advise if possible and extend readme .

**Comment by boeserfrosch** [comment]
Thank you, good advice. I have added a corresponding passage to the ReadMe. 
In fact, according to the data sheet, the heater should be switched on if condensation occurs due to high humidity.
